import { DTCCode, DTCCategory, DTCSeverity } from '@/types';

const dtcDatabase: DTCCode[] = [
  // ===== POWERTRAIN (P) CODES =====
  // P0xxx - Generic Powertrain
  { code: 'P0010', description: 'Intake Camshaft Position Actuator Circuit / Open (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Variable Valve Timing',
    possibleCauses: ['Faulty camshaft position actuator solenoid', 'Wiring harness damage', 'Low engine oil level', 'Dirty engine oil', 'ECM failure'],
    symptoms: ['Check engine light', 'Rough idle', 'Reduced fuel economy', 'Engine hesitation'],
    solutions: ['Check and replace engine oil', 'Inspect wiring harness', 'Replace camshaft position actuator solenoid', 'Check ECM'],
    estimatedCost: { min: 40, max: 350 } },
  { code: 'P0011', description: 'Intake Camshaft Position Timing - Over-Advanced (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Variable Valve Timing',
    possibleCauses: ['Dirty engine oil', 'Low oil level', 'Faulty VVT solenoid', 'Timing chain stretched', 'ECM issue'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Rough idle', 'Hard starting'],
    solutions: ['Change engine oil and filter', 'Replace VVT solenoid', 'Check timing chain', 'Inspect oil control valve'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0012', description: 'Intake Camshaft Position Timing - Over-Retarded (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Variable Valve Timing',
    possibleCauses: ['Dirty engine oil', 'Faulty VVT solenoid', 'Timing chain issue', 'Oil control valve stuck'],
    symptoms: ['Check engine light', 'Rough idle', 'Poor acceleration', 'Stalling'],
    solutions: ['Oil and filter change', 'Replace VVT solenoid', 'Check timing chain tensioner'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0016', description: 'Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)', category: 'powertrain', severity: 'critical', system: 'Engine Timing',
    possibleCauses: ['Stretched timing chain', 'Faulty crankshaft position sensor', 'Faulty camshaft position sensor', 'Oil control valve issue'],
    symptoms: ['Check engine light', 'Engine misfires', 'Rough running', 'Reduced power'],
    solutions: ['Replace timing chain and tensioner', 'Replace crankshaft/camshaft position sensor', 'Check wiring'],
    estimatedCost: { min: 200, max: 1500 } },
  { code: 'P0030', description: 'HO2S Heater Control Circuit (Bank 1, Sensor 1)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Faulty oxygen sensor', 'Wiring issue', 'Blown fuse', 'ECM problem'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Failed emissions test'],
    solutions: ['Replace oxygen sensor', 'Check wiring and connectors', 'Check fuse'],
    estimatedCost: { min: 100, max: 350 } },
  { code: 'P0100', description: 'Mass or Volume Air Flow Circuit Malfunction', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty MAF sensor', 'Faulty MAF sensor', 'Vacuum leak', 'Wiring issue'],
    symptoms: ['Check engine light', 'Rough idle', 'Stalling', 'Hard starting', 'Poor acceleration'],
    solutions: ['Clean MAF sensor', 'Replace MAF sensor', 'Check for vacuum leaks', 'Inspect wiring'],
    estimatedCost: { min: 30, max: 400 } },
  { code: 'P0101', description: 'Mass or Volume Air Flow Circuit Range/Performance Problem', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty MAF sensor', 'Air filter restriction', 'Vacuum leak', 'Faulty MAF sensor'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Rough idle', 'Hesitation'],
    solutions: ['Clean or replace MAF sensor', 'Replace air filter', 'Check for vacuum leaks'],
    estimatedCost: { min: 20, max: 400 } },
  { code: 'P0102', description: 'Mass or Volume Air Flow Circuit Low Input', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty MAF sensor', 'Vacuum leak', 'Restricted air filter', 'Wiring issue'],
    symptoms: ['Check engine light', 'Stalling', 'Hard starting', 'Rough idle'],
    solutions: ['Clean or replace MAF sensor', 'Check air filter', 'Inspect wiring'],
    estimatedCost: { min: 20, max: 350 } },
  { code: 'P0113', description: 'Intake Air Temperature Circuit High Input', category: 'powertrain', severity: 'info', system: 'Fuel System',
    possibleCauses: ['Faulty IAT sensor', 'Open circuit', 'Poor connection', 'Damaged wiring'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Hard cold start'],
    solutions: ['Replace IAT sensor', 'Check wiring and connectors'],
    estimatedCost: { min: 30, max: 150 } },
  { code: 'P0128', description: 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)', category: 'powertrain', severity: 'warning', system: 'Cooling System',
    possibleCauses: ['Stuck-open thermostat', 'Faulty coolant temperature sensor', 'Low coolant level', 'Faulty thermostat housing'],
    symptoms: ['Check engine light', 'Engine runs cool', 'Poor heater performance', 'Higher fuel consumption'],
    solutions: ['Replace thermostat', 'Replace coolant temperature sensor', 'Check coolant level'],
    estimatedCost: { min: 80, max: 300 } },
  { code: 'P0133', description: 'O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Faulty oxygen sensor', 'Exhaust leak', 'Vacuum leak', 'Fuel pressure issue'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Rough idle', 'Failed emissions'],
    solutions: ['Replace O2 sensor', 'Check for exhaust leaks', 'Check for vacuum leaks'],
    estimatedCost: { min: 100, max: 350 } },
  { code: 'P0171', description: 'System Too Lean (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Vacuum leak', 'Dirty MAF sensor', 'Weak fuel pump', 'Clogged fuel injectors', 'Exhaust leak'],
    symptoms: ['Check engine light', 'Rough idle', 'Hesitation', 'Misfires', 'Poor fuel economy'],
    solutions: ['Check for vacuum leaks', 'Clean MAF sensor', 'Replace fuel filter', 'Clean fuel injectors', 'Check fuel pressure'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0172', description: 'System Too Rich (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty air filter', 'Faulty MAF sensor', 'Leaking fuel injector', 'Faulty O2 sensor', 'High fuel pressure'],
    symptoms: ['Check engine light', 'Black exhaust smoke', 'Poor fuel economy', 'Rough idle', 'Strong fuel smell'],
    solutions: ['Replace air filter', 'Clean/replace MAF sensor', 'Check fuel injectors', 'Replace O2 sensor'],
    estimatedCost: { min: 20, max: 450 } },
  { code: 'P0174', description: 'System Too Lean (Bank 2)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Vacuum leak', 'Dirty MAF sensor', 'Weak fuel pump', 'Clogged fuel injectors'],
    symptoms: ['Check engine light', 'Rough idle', 'Hesitation', 'Misfires'],
    solutions: ['Check for vacuum leaks', 'Clean MAF sensor', 'Check fuel pressure', 'Clean fuel injectors'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0175', description: 'System Too Rich (Bank 2)', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty air filter', 'Faulty MAF sensor', 'Leaking fuel injector', 'Faulty fuel pressure regulator'],
    symptoms: ['Check engine light', 'Black smoke', 'Poor fuel economy', 'Rough idle'],
    solutions: ['Replace air filter', 'Clean/replace MAF sensor', 'Check fuel injectors', 'Check fuel pressure regulator'],
    estimatedCost: { min: 20, max: 450 } },
  { code: 'P0200', description: 'Injector Circuit Malfunction', category: 'powertrain', severity: 'critical', system: 'Fuel System',
    possibleCauses: ['Faulty fuel injector', 'Wiring harness issue', 'ECM problem', 'Poor electrical connection'],
    symptoms: ['Check engine light', 'Engine misfires', 'Rough idle', 'Loss of power'],
    solutions: ['Check injector wiring', 'Replace fuel injector', 'Check ECM'],
    estimatedCost: { min: 150, max: 600 } },
  { code: 'P0300', description: 'Random/Multiple Cylinder Misfire Detected', category: 'powertrain', severity: 'critical', system: 'Ignition System',
    possibleCauses: ['Worn spark plugs', 'Faulty ignition coils', 'Vacuum leak', 'Low fuel pressure', 'Intake manifold gasket leak', 'Low compression'],
    symptoms: ['Check engine light (flashing)', 'Rough idle', 'Loss of power', 'Vibration', 'Poor fuel economy'],
    solutions: ['Replace spark plugs', 'Replace ignition coils', 'Check for vacuum leaks', 'Check fuel pressure', 'Compression test'],
    estimatedCost: { min: 100, max: 1000 } },
  { code: 'P0301', description: 'Cylinder 1 Misfire Detected', category: 'powertrain', severity: 'critical', system: 'Ignition System',
    possibleCauses: ['Worn spark plug', 'Faulty ignition coil', 'Fuel injector issue', 'Low compression', 'Vacuum leak'],
    symptoms: ['Check engine light', 'Rough idle', 'Loss of power on cylinder 1', 'Engine vibration'],
    solutions: ['Replace spark plug', 'Replace ignition coil', 'Check fuel injector', 'Compression test'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0302', description: 'Cylinder 2 Misfire Detected', category: 'powertrain', severity: 'critical', system: 'Ignition System',
    possibleCauses: ['Worn spark plug', 'Faulty ignition coil', 'Fuel injector issue', 'Low compression'],
    symptoms: ['Check engine light', 'Rough idle', 'Loss of power', 'Vibration'],
    solutions: ['Replace spark plug', 'Replace ignition coil', 'Check fuel injector', 'Compression test'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0303', description: 'Cylinder 3 Misfire Detected', category: 'powertrain', severity: 'critical', system: 'Ignition System',
    possibleCauses: ['Worn spark plug', 'Faulty ignition coil', 'Fuel injector issue', 'Low compression'],
    symptoms: ['Check engine light', 'Rough idle', 'Loss of power', 'Vibration'],
    solutions: ['Replace spark plug', 'Replace ignition coil', 'Check fuel injector'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0304', description: 'Cylinder 4 Misfire Detected', category: 'powertrain', severity: 'critical', system: 'Ignition System',
    possibleCauses: ['Worn spark plug', 'Faulty ignition coil', 'Fuel injector issue', 'Low compression'],
    symptoms: ['Check engine light', 'Rough idle', 'Loss of power', 'Vibration'],
    solutions: ['Replace spark plug', 'Replace ignition coil', 'Check fuel injector'],
    estimatedCost: { min: 50, max: 500 } },
  { code: 'P0325', description: 'Knock Sensor 1 Circuit Malfunction (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Ignition System',
    possibleCauses: ['Faulty knock sensor', 'Wiring issue', 'ECM problem', 'Engine mechanical issue'],
    symptoms: ['Check engine light', 'Engine pinging/knocking', 'Reduced fuel economy'],
    solutions: ['Replace knock sensor', 'Check wiring', 'Use correct octane fuel'],
    estimatedCost: { min: 150, max: 500 } },
  { code: 'P0340', description: 'Camshaft Position Sensor Circuit Malfunction', category: 'powertrain', severity: 'critical', system: 'Engine Timing',
    possibleCauses: ['Faulty camshaft position sensor', 'Wiring issue', 'Timing chain/belt problem', 'ECM failure'],
    symptoms: ['Check engine light', 'No start condition', 'Stalling', 'Rough running'],
    solutions: ['Replace camshaft position sensor', 'Check wiring and connector', 'Inspect timing components'],
    estimatedCost: { min: 80, max: 350 } },
  { code: 'P0400', description: 'Exhaust Gas Recirculation Flow Malfunction', category: 'powertrain', severity: 'warning', system: 'Emissions System',
    possibleCauses: ['Clogged EGR valve', 'Faulty EGR valve', 'Carbon buildup', 'EGR passage blocked'],
    symptoms: ['Check engine light', 'Rough idle', 'Engine ping', 'Failed emissions test'],
    solutions: ['Clean EGR valve', 'Replace EGR valve', 'Clean EGR passages'],
    estimatedCost: { min: 100, max: 500 } },
  { code: 'P0401', description: 'Exhaust Gas Recirculation Flow Insufficient Detected', category: 'powertrain', severity: 'warning', system: 'Emissions System',
    possibleCauses: ['Clogged EGR passages', 'Faulty EGR valve', 'Faulty DPFE sensor', 'Carbon buildup'],
    symptoms: ['Check engine light', 'Engine knock', 'Failed emissions', 'Increased NOx emissions'],
    solutions: ['Clean EGR valve and passages', 'Replace EGR valve', 'Replace DPFE sensor'],
    estimatedCost: { min: 100, max: 450 } },
  { code: 'P0420', description: 'Catalyst System Efficiency Below Threshold (Bank 1)', category: 'powertrain', severity: 'warning', system: 'Emissions System',
    possibleCauses: ['Failing catalytic converter', 'Faulty O2 sensor', 'Exhaust leak', 'Engine misfire damage', 'Rich/lean condition'],
    symptoms: ['Check engine light', 'Failed emissions test', 'Reduced performance', 'Sulfur smell'],
    solutions: ['Replace catalytic converter', 'Replace downstream O2 sensor', 'Fix exhaust leaks', 'Address root cause misfires'],
    estimatedCost: { min: 200, max: 2500 } },
  { code: 'P0430', description: 'Catalyst System Efficiency Below Threshold (Bank 2)', category: 'powertrain', severity: 'warning', system: 'Emissions System',
    possibleCauses: ['Failing catalytic converter', 'Faulty O2 sensor', 'Exhaust leak'],
    symptoms: ['Check engine light', 'Failed emissions test', 'Reduced performance'],
    solutions: ['Replace catalytic converter', 'Replace downstream O2 sensor', 'Fix exhaust leaks'],
    estimatedCost: { min: 200, max: 2500 } },
  { code: 'P0440', description: 'Evaporative Emission Control System Malfunction', category: 'powertrain', severity: 'info', system: 'EVAP System',
    possibleCauses: ['Loose gas cap', 'Faulty EVAP canister', 'Leaking EVAP hose', 'Faulty purge valve'],
    symptoms: ['Check engine light', 'Fuel smell', 'Failed emissions test'],
    solutions: ['Tighten or replace gas cap', 'Check EVAP system for leaks', 'Replace purge valve'],
    estimatedCost: { min: 10, max: 400 } },
  { code: 'P0441', description: 'Evaporative Emission Control System Incorrect Purge Flow', category: 'powertrain', severity: 'info', system: 'EVAP System',
    possibleCauses: ['Faulty purge valve', 'EVAP leak', 'Damaged EVAP canister', 'Wiring issue'],
    symptoms: ['Check engine light', 'Slight fuel smell'],
    solutions: ['Replace purge valve', 'Check EVAP system for leaks', 'Replace EVAP canister'],
    estimatedCost: { min: 50, max: 350 } },
  { code: 'P0442', description: 'Evaporative Emission Control System Leak Detected (Small Leak)', category: 'powertrain', severity: 'info', system: 'EVAP System',
    possibleCauses: ['Loose gas cap', 'Small EVAP leak', 'Cracked EVAP hose', 'Faulty vent valve'],
    symptoms: ['Check engine light'],
    solutions: ['Tighten gas cap', 'Smoke test EVAP system', 'Replace leaking components'],
    estimatedCost: { min: 10, max: 350 } },
  { code: 'P0443', description: 'Evaporative Emission Control System Purge Control Valve Circuit Malfunction', category: 'powertrain', severity: 'info', system: 'EVAP System',
    possibleCauses: ['Faulty purge valve', 'Wiring issue', 'ECM problem'],
    symptoms: ['Check engine light', 'Failed emissions test'],
    solutions: ['Replace purge valve', 'Check wiring'],
    estimatedCost: { min: 50, max: 250 } },
  { code: 'P0446', description: 'Evaporative Emission Control System Vent Control Circuit Malfunction', category: 'powertrain', severity: 'info', system: 'EVAP System',
    possibleCauses: ['Faulty vent valve', 'Blocked EVAP canister vent', 'Wiring issue'],
    symptoms: ['Check engine light', 'Difficulty filling fuel tank'],
    solutions: ['Replace vent valve', 'Check vent line', 'Inspect wiring'],
    estimatedCost: { min: 50, max: 300 } },
  { code: 'P0455', description: 'Evaporative Emission Control System Leak Detected (Gross Leak)', category: 'powertrain', severity: 'warning', system: 'EVAP System',
    possibleCauses: ['Missing or loose gas cap', 'Disconnected EVAP hose', 'Cracked EVAP canister', 'Faulty purge/vent valve'],
    symptoms: ['Check engine light', 'Strong fuel smell', 'Failed emissions'],
    solutions: ['Replace gas cap', 'Check all EVAP hoses', 'Smoke test system'],
    estimatedCost: { min: 10, max: 400 } },
  { code: 'P0500', description: 'Vehicle Speed Sensor Malfunction', category: 'powertrain', severity: 'warning', system: 'Transmission',
    possibleCauses: ['Faulty VSS', 'Wiring issue', 'Damaged tone ring', 'ECM/TCM problem'],
    symptoms: ['Check engine light', 'Speedometer not working', 'Transmission shifting issues', 'ABS/traction control light'],
    solutions: ['Replace vehicle speed sensor', 'Check wiring', 'Inspect tone ring'],
    estimatedCost: { min: 100, max: 350 } },
  { code: 'P0505', description: 'Idle Control System Malfunction', category: 'powertrain', severity: 'warning', system: 'Fuel System',
    possibleCauses: ['Dirty throttle body', 'Faulty idle air control valve', 'Vacuum leak', 'Wiring issue'],
    symptoms: ['Rough/unstable idle', 'Stalling', 'Check engine light', 'RPM fluctuation'],
    solutions: ['Clean throttle body', 'Replace idle air control valve', 'Check for vacuum leaks'],
    estimatedCost: { min: 50, max: 350 } },
  { code: 'P0507', description: 'Idle Control System RPM Higher Than Expected', category: 'powertrain', severity: 'info', system: 'Fuel System',
    possibleCauses: ['Vacuum leak', 'Dirty throttle body', 'Faulty IACV', 'PCV valve issue'],
    symptoms: ['High idle speed', 'Check engine light'],
    solutions: ['Check for vacuum leaks', 'Clean throttle body', 'Replace IACV'],
    estimatedCost: { min: 30, max: 300 } },
  { code: 'P0562', description: 'System Voltage Low', category: 'powertrain', severity: 'warning', system: 'Electrical System',
    possibleCauses: ['Weak battery', 'Faulty alternator', 'Corroded battery terminals', 'Wiring issue', 'Parasitic draw'],
    symptoms: ['Check engine light', 'Dim lights', 'Electrical issues', 'Hard starting'],
    solutions: ['Test and replace battery', 'Test and replace alternator', 'Clean battery terminals'],
    estimatedCost: { min: 100, max: 600 } },
  { code: 'P0600', description: 'Serial Communication Link Malfunction', category: 'powertrain', severity: 'critical', system: 'Control Module',
    possibleCauses: ['ECM internal failure', 'Wiring harness issue', 'Poor ground connection', 'CAN bus problem'],
    symptoms: ['Check engine light', 'Multiple warning lights', 'Various drivability issues'],
    solutions: ['Check wiring harness', 'Check grounds', 'Reprogram/replace ECM'],
    estimatedCost: { min: 200, max: 1500 } },
  { code: 'P0700', description: 'Transmission Control System Malfunction', category: 'powertrain', severity: 'critical', system: 'Transmission',
    possibleCauses: ['TCM failure', 'Wiring issue', 'Internal transmission problem', 'Low transmission fluid'],
    symptoms: ['Check engine light', 'Transmission warning light', 'Harsh shifting', 'Limp mode'],
    solutions: ['Check transmission fluid', 'Scan for specific transmission codes', 'Check TCM wiring', 'Transmission service'],
    estimatedCost: { min: 150, max: 3000 } },
  { code: 'P0705', description: 'Transmission Range Sensor Circuit Malfunction', category: 'powertrain', severity: 'warning', system: 'Transmission',
    possibleCauses: ['Faulty range sensor', 'Adjustment needed', 'Wiring issue', 'TCM problem'],
    symptoms: ['Check engine light', 'Incorrect gear display', 'No start in Park/Neutral', 'Harsh shifts'],
    solutions: ['Adjust or replace range sensor', 'Check wiring', 'Check TCM'],
    estimatedCost: { min: 100, max: 500 } },
  { code: 'P0715', description: 'Input/Turbine Speed Sensor Circuit Malfunction', category: 'powertrain', severity: 'warning', system: 'Transmission',
    possibleCauses: ['Faulty input speed sensor', 'Wiring issue', 'Damaged connector', 'Internal transmission issue'],
    symptoms: ['Check engine light', 'Harsh shifting', 'Speedometer issues', 'No overdrive'],
    solutions: ['Replace input speed sensor', 'Check wiring and connector'],
    estimatedCost: { min: 100, max: 400 } },
  { code: 'P0720', description: 'Output Speed Sensor Circuit Malfunction', category: 'powertrain', severity: 'warning', system: 'Transmission',
    possibleCauses: ['Faulty output speed sensor', 'Wiring issue', 'Damaged tone ring', 'TCM issue'],
    symptoms: ['Check engine light', 'Erratic shifting', 'Speedometer malfunction'],
    solutions: ['Replace output speed sensor', 'Check wiring', 'Inspect tone ring'],
    estimatedCost: { min: 100, max: 400 } },
  { code: 'P0741', description: 'Torque Converter Clutch Circuit Performance or Stuck Off', category: 'powertrain', severity: 'warning', system: 'Transmission',
    possibleCauses: ['Faulty TCC solenoid', 'Dirty transmission fluid', 'Internal transmission wear', 'Wiring issue'],
    symptoms: ['Check engine light', 'Poor fuel economy', 'Slight shudder at highway speed', 'Overheating'],
    solutions: ['Transmission fluid flush', 'Replace TCC solenoid', 'Rebuild transmission'],
    estimatedCost: { min: 150, max: 2500 } },

  // ===== BODY (B) CODES =====
  { code: 'B0001', description: 'Driver Frontal Stage 1 Deployment Control', category: 'body', severity: 'critical', system: 'Airbag System',
    possibleCauses: ['Faulty airbag module', 'Clockspring failure', 'Wiring damage', 'ACM failure'],
    symptoms: ['Airbag warning light', 'SRS light on'],
    solutions: ['Replace airbag module', 'Replace clockspring', 'Check wiring', 'Replace ACM'],
    estimatedCost: { min: 200, max: 1500 } },
  { code: 'B0100', description: 'Electronic Frontal Sensor 1 Performance', category: 'body', severity: 'critical', system: 'Airbag System',
    possibleCauses: ['Faulty crash sensor', 'Wiring issue', 'Sensor mounting problem'],
    symptoms: ['Airbag warning light', 'SRS malfunction'],
    solutions: ['Replace crash sensor', 'Check wiring and mounting'],
    estimatedCost: { min: 100, max: 500 } },
  { code: 'B1000', description: 'ECU Malfunction - Internal', category: 'body', severity: 'warning', system: 'Body Control Module',
    possibleCauses: ['Faulty BCM', 'Software issue', 'Voltage supply problem'],
    symptoms: ['Various electrical malfunctions', 'Warning lights'],
    solutions: ['Reprogram BCM', 'Replace BCM', 'Check voltage supply'],
    estimatedCost: { min: 200, max: 800 } },
  { code: 'B1318', description: 'Battery Voltage Low', category: 'body', severity: 'warning', system: 'Electrical System',
    possibleCauses: ['Weak battery', 'Charging system issue', 'Parasitic drain', 'Corroded terminals'],
    symptoms: ['Warning lights', 'Electrical malfunctions', 'Dim lights'],
    solutions: ['Test/replace battery', 'Check alternator', 'Clean terminals'],
    estimatedCost: { min: 100, max: 400 } },
  { code: 'B1342', description: 'ECU Internal Temperature Too High', category: 'body', severity: 'warning', system: 'Body Control Module',
    possibleCauses: ['Overheating BCM', 'Poor ventilation', 'High ambient temperature'],
    symptoms: ['Intermittent electrical issues', 'Warning lights'],
    solutions: ['Check BCM ventilation', 'Relocate if aftermarket', 'Replace BCM'],
    estimatedCost: { min: 150, max: 600 } },
  { code: 'B1600', description: 'PATS Received Incorrect Key Code', category: 'body', severity: 'warning', system: 'Anti-Theft System',
    possibleCauses: ['Wrong key', 'Faulty key transponder', 'PATS module issue', 'Key not programmed'],
    symptoms: ['No start', 'Theft indicator flashing', 'Security light on'],
    solutions: ['Reprogram key', 'Replace key transponder', 'Check PATS module'],
    estimatedCost: { min: 50, max: 400 } },
  { code: 'B2799', description: 'Engine Immobilizer System Malfunction', category: 'body', severity: 'critical', system: 'Anti-Theft System',
    possibleCauses: ['Key transponder failure', 'Immobilizer module fault', 'Wiring issue', 'ECM communication error'],
    symptoms: ['No start', 'Security light on', 'Engine cranks but won\'t start'],
    solutions: ['Reprogram key', 'Replace immobilizer module', 'Check wiring'],
    estimatedCost: { min: 100, max: 600 } },

  // ===== CHASSIS (C) CODES =====
  { code: 'C0035', description: 'Left Front Wheel Speed Circuit Malfunction', category: 'chassis', severity: 'warning', system: 'ABS System',
    possibleCauses: ['Faulty wheel speed sensor', 'Damaged tone ring', 'Wiring issue', 'Sensor gap too large'],
    symptoms: ['ABS warning light', 'Traction control light', 'ABS not functioning'],
    solutions: ['Replace wheel speed sensor', 'Check tone ring', 'Inspect wiring'],
    estimatedCost: { min: 80, max: 350 } },
  { code: 'C0040', description: 'Right Front Wheel Speed Circuit Malfunction', category: 'chassis', severity: 'warning', system: 'ABS System',
    possibleCauses: ['Faulty wheel speed sensor', 'Damaged tone ring', 'Wiring issue'],
    symptoms: ['ABS warning light', 'Traction control light', 'ABS not functioning'],
    solutions: ['Replace wheel speed sensor', 'Check tone ring', 'Inspect wiring'],
    estimatedCost: { min: 80, max: 350 } },
  { code: 'C0050', description: 'Left Rear Wheel Speed Circuit Malfunction', category: 'chassis', severity: 'warning', system: 'ABS System',
    possibleCauses: ['Faulty wheel speed sensor', 'Damaged tone ring', 'Wiring corrosion'],
    symptoms: ['ABS light', 'Traction control disabled'],
    solutions: ['Replace wheel speed sensor', 'Clean/replace wiring'],
    estimatedCost: { min: 80, max: 350 } },
  { code: 'C0055', description: 'Right Rear Wheel Speed Circuit Malfunction', category: 'chassis', severity: 'warning', system: 'ABS System',
    possibleCauses: ['Faulty wheel speed sensor', 'Damaged tone ring', 'Wiring issue'],
    symptoms: ['ABS light', 'Traction control disabled'],
    solutions: ['Replace wheel speed sensor', 'Inspect tone ring'],
    estimatedCost: { min: 80, max: 350 } },
  { code: 'C0265', description: 'EBCM Motor Relay Circuit', category: 'chassis', severity: 'critical', system: 'ABS System',
    possibleCauses: ['Faulty ABS module', 'Motor relay failure', 'Wiring issue', 'Low voltage'],
    symptoms: ['ABS light', 'Traction control light', 'Brake warning light', 'ABS pump running constantly'],
    solutions: ['Replace ABS module', 'Check relay and wiring', 'Check battery voltage'],
    estimatedCost: { min: 300, max: 1500 } },
  { code: 'C1095', description: 'ABS Hydraulic Pump Motor Circuit Failure', category: 'chassis', severity: 'critical', system: 'ABS System',
    possibleCauses: ['Faulty ABS pump motor', 'ABS module failure', 'Wiring issue', 'Low brake fluid'],
    symptoms: ['ABS light', 'Brake warning light', 'Reduced braking assistance'],
    solutions: ['Replace ABS pump/module', 'Check brake fluid', 'Inspect wiring'],
    estimatedCost: { min: 400, max: 2000 } },
  { code: 'C1201', description: 'Engine Control System Malfunction', category: 'chassis', severity: 'warning', system: 'Vehicle Stability',
    possibleCauses: ['Engine DTC present', 'VSC system responding to engine fault', 'ECM communication issue'],
    symptoms: ['VSC light', 'Check engine light', 'Traction control light'],
    solutions: ['Diagnose and fix engine DTCs first', 'Clear codes after engine repair'],
    estimatedCost: { min: 0, max: 500 } },
  { code: 'C1234', description: 'Wheel Speed Signal Missing - Left Front', category: 'chassis', severity: 'warning', system: 'ABS System',
    possibleCauses: ['Faulty ABS sensor', 'Wiring break', 'ABS ring damage', 'Connector corrosion'],
    symptoms: ['ABS light', 'Stability control disabled', 'Speedometer fluctuation'],
    solutions: ['Replace ABS sensor', 'Repair wiring', 'Replace ABS ring'],
    estimatedCost: { min: 80, max: 400 } },

  // ===== NETWORK (U) CODES =====
  { code: 'U0001', description: 'High Speed CAN Communication Bus', category: 'network', severity: 'critical', system: 'Communication Network',
    possibleCauses: ['CAN bus wiring short/open', 'Faulty module on bus', 'Damaged CAN bus terminator', 'ECM failure'],
    symptoms: ['Multiple warning lights', 'No communication with modules', 'Various system failures'],
    solutions: ['Check CAN bus wiring', 'Test each module', 'Check bus terminators', 'Replace faulty module'],
    estimatedCost: { min: 100, max: 2000 } },
  { code: 'U0073', description: 'Control Module Communication Bus Off', category: 'network', severity: 'critical', system: 'Communication Network',
    possibleCauses: ['CAN bus failure', 'Module pulling bus down', 'Wiring short', 'Faulty termination'],
    symptoms: ['Multiple warning lights', 'Various systems inoperative', 'No scan tool communication'],
    solutions: ['Isolate faulty module', 'Check bus wiring', 'Replace faulty module'],
    estimatedCost: { min: 200, max: 2000 } },
  { code: 'U0100', description: 'Lost Communication with ECM/PCM "A"', category: 'network', severity: 'critical', system: 'Communication Network',
    possibleCauses: ['ECM failure', 'CAN bus wiring issue', 'Power/ground issue to ECM', 'Connector corrosion'],
    symptoms: ['No start', 'Multiple warning lights', 'Limp mode'],
    solutions: ['Check ECM power and grounds', 'Inspect CAN bus wiring', 'Replace ECM if necessary'],
    estimatedCost: { min: 100, max: 1500 } },
  { code: 'U0101', description: 'Lost Communication with TCM', category: 'network', severity: 'critical', system: 'Communication Network',
    possibleCauses: ['TCM failure', 'CAN bus wiring issue', 'Power/ground issue', 'Connector problem'],
    symptoms: ['Transmission warning light', 'Limp mode', 'No shifting'],
    solutions: ['Check TCM power/grounds', 'Inspect wiring', 'Replace TCM'],
    estimatedCost: { min: 150, max: 1500 } },
  { code: 'U0121', description: 'Lost Communication with Anti-Lock Brake System Module', category: 'network', severity: 'critical', system: 'Communication Network',
    possibleCauses: ['ABS module failure', 'Wiring issue', 'CAN bus problem'],
    symptoms: ['ABS light', 'Traction control light', 'Stability control light'],
    solutions: ['Check ABS module wiring', 'Replace ABS module'],
    estimatedCost: { min: 200, max: 1500 } },
  { code: 'U0140', description: 'Lost Communication with Body Control Module', category: 'network', severity: 'warning', system: 'Communication Network',
    possibleCauses: ['BCM failure', 'Wiring issue', 'CAN bus problem', 'Power supply issue'],
    symptoms: ['Various electrical issues', 'Warning lights', 'Accessory malfunctions'],
    solutions: ['Check BCM power/grounds', 'Inspect wiring', 'Replace BCM'],
    estimatedCost: { min: 150, max: 1000 } },
  { code: 'U0155', description: 'Lost Communication with Instrument Panel Cluster', category: 'network', severity: 'warning', system: 'Communication Network',
    possibleCauses: ['IPC failure', 'Wiring issue', 'CAN bus problem'],
    symptoms: ['No instrument cluster display', 'Gauges not working', 'Warning lights stuck'],
    solutions: ['Check IPC wiring', 'Replace instrument cluster', 'Check CAN bus'],
    estimatedCost: { min: 200, max: 1000 } },
  { code: 'U0401', description: 'Invalid Data Received from ECM/PCM', category: 'network', severity: 'warning', system: 'Communication Network',
    possibleCauses: ['ECM software issue', 'CAN bus interference', 'ECM hardware degradation'],
    symptoms: ['Intermittent warning lights', 'Unexpected behavior', 'Drivability issues'],
    solutions: ['Update ECM software', 'Check CAN bus integrity', 'Replace ECM'],
    estimatedCost: { min: 100, max: 1000 } },
];

export function searchDTCByCode(code: string): DTCCode | undefined {
  return dtcDatabase.find(d => d.code.toLowerCase() === code.toLowerCase());
}

export function searchDTCByKeyword(keyword: string): DTCCode[] {
  const lower = keyword.toLowerCase();
  return dtcDatabase.filter(d =>
    d.code.toLowerCase().includes(lower) ||
    d.description.toLowerCase().includes(lower) ||
    d.system.toLowerCase().includes(lower) ||
    d.possibleCauses.some(c => c.toLowerCase().includes(lower)) ||
    d.symptoms.some(s => s.toLowerCase().includes(lower))
  );
}

export function getDTCsByCategory(category: DTCCategory): DTCCode[] {
  return dtcDatabase.filter(d => d.category === category);
}

export function getDTCsBySeverity(severity: DTCSeverity): DTCCode[] {
  return dtcDatabase.filter(d => d.severity === severity);
}

export function getDTCsBySystem(system: string): DTCCode[] {
  return dtcDatabase.filter(d => d.system.toLowerCase() === system.toLowerCase());
}

export function getAllSystems(): string[] {
  return Array.from(new Set(dtcDatabase.map(d => d.system))).sort();
}

export function getAllDTCs(): DTCCode[] {
  return dtcDatabase;
}

export function interpretDTCCode(code: string): { prefix: string; category: DTCCategory; type: string; number: string } | null {
  const match = code.match(/^([PBCU])(\d)(\d{3})$/i);
  if (!match) return null;

  const prefixMap: Record<string, DTCCategory> = { P: 'powertrain', B: 'body', C: 'chassis', U: 'network' };
  const typeMap: Record<string, string> = { '0': 'Generic (SAE)', '1': 'Manufacturer-Specific', '2': 'Generic (SAE)', '3': 'Manufacturer/Generic' };

  return {
    prefix: match[1].toUpperCase(),
    category: prefixMap[match[1].toUpperCase()],
    type: typeMap[match[2]] || 'Unknown',
    number: match[3],
  };
}
